import { z } from "zod";

/**
 * Business ids are minted by this app (generateBookingId) or by seed.sql, so
 * they are never uuids (fix_plan B4). One schema, every consumer:
 * `GET /api/bookings/[id]`, `payments/{create-intent,refund,confirm}`.
 *
 *   BOOKING001-20260928   generated by src/lib/generate-id.ts
 *   BKG-001               seeded by artifacts/seed.sql
 *   <uuid>                legacy rows / fixtures (kept as a superset so no
 *                         existing caller regresses)
 */
const BOOKING_ID_PATTERN =
  /^(BOOKING\d{3}-\d{8}|BKG-\d{3}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i;

export const bookingIdSchema = z
  .string()
  .regex(BOOKING_ID_PATTERN, "Invalid booking ID format");

export type BookingId = z.infer<typeof bookingIdSchema>;
